// SEO 选题库 - 围绕核心业务关键词的长尾词矩阵
// 每次生成时随机选取一个未使用的选题，调用 AI 生成原创文章
module.exports = {
  // 站点基础信息（生成文章内链、CTA 时使用）
  site: {
    name: '叮当跨境ERP',
    url: 'https://www.ddddnet.cn',
    appUrl: 'https://ddddnet.cn',
    desc: 'Temu半托管POD智能套图系统',
  },
  // 选题列表：topic=主题方向, keywords=SEO关键词, category=分类
  topics: [
    // ===== Temu 运营 =====
    { topic: 'Temu半托管上品完整流程教程', keywords: ['Temu半托管', '上品教程', 'Temu运营'], category: 'Temu运营' },
    { topic: 'Temu半托管和全托管的区别与选择', keywords: ['Temu半托管', '全托管', 'Temu模式'], category: 'Temu运营' },
    { topic: 'Temu半托管卖家如何提升上架效率', keywords: ['Temu半托管', '上架效率', '批量上品'], category: 'Temu运营' },
    { topic: 'Temu选品技巧与爆款挖掘方法', keywords: ['Temu选品', '爆款', '选品技巧'], category: 'Temu运营' },
    { topic: 'Temu半托管物流发货注意事项', keywords: ['Temu半托管', '物流发货', '发货流程'], category: 'Temu运营' },
    { topic: 'Temu新品如何快速获取流量', keywords: ['Temu流量', '新品推广', 'Temu运营'], category: 'Temu运营' },
    { topic: 'Temu半托管售后处理与评分维护', keywords: ['Temu售后', '评分维护', '半托管'], category: 'Temu运营' },
    { topic: 'Temu平台规则解读与避坑指南', keywords: ['Temu规则', '避坑', '平台政策'], category: 'Temu运营' },
    { topic: 'Temu半托管定价策略与利润计算', keywords: ['Temu定价', '利润计算', '半托管'], category: 'Temu运营' },
    { topic: 'Temu活动报名与大促备战指南', keywords: ['Temu活动', '大促', '报名'], category: 'Temu运营' },
    { topic: 'Temu半托管备货与库存管理技巧', keywords: ['Temu备货', '库存管理', '半托管'], category: 'Temu运营' },
    { topic: 'Temu商品主图设计规范与技巧', keywords: ['Temu主图', '商品图', '图片规范'], category: 'Temu运营' },
    { topic: 'Temu详情页优化提升转化率', keywords: ['Temu详情页', '转化率', '页面优化'], category: 'Temu运营' },
    { topic: 'Temu半托管入驻条件与流程', keywords: ['Temu入驻', '半托管', '开店流程'], category: 'Temu运营' },
    { topic: 'Temu卖家常见拒审原因与解决方案', keywords: ['Temu拒审', '审核', '上架失败'], category: 'Temu运营' },

    // ===== POD 套图 =====
    { topic: 'POD套图模板设计入门指南', keywords: ['POD套图', '模板设计', '套图教程'], category: 'POD套图' },
    { topic: '批量套图工具对比与选择', keywords: ['批量套图', '套图工具', '工具对比'], category: 'POD套图' },
    { topic: 'POD印花图案制作技巧大全', keywords: ['POD印花', '图案制作', '设计技巧'], category: 'POD套图' },
    { topic: '如何设计高转化率的商品套图模板', keywords: ['套图模板', '转化率', '商品图设计'], category: 'POD套图' },
    { topic: 'POD套图中主图与细节图的处理方法', keywords: ['POD套图', '主图', '细节图'], category: 'POD套图' },
    { topic: '套图模板的印花区域如何精准定位', keywords: ['套图模板', '印花区域', '精准定位'], category: 'POD套图' },
    { topic: 'POD套图常见的填充模式与应用场景', keywords: ['POD套图', '填充模式', '裁切适应'], category: 'POD套图' },
    { topic: '如何用套图工具提升上品速度', keywords: ['套图工具', '上品速度', '批量出图'], category: 'POD套图' },
    { topic: 'POD图案设计灵感与素材来源', keywords: ['POD图案', '设计灵感', '素材'], category: 'POD套图' },
    { topic: '套图导出ZIP打包的正确方式', keywords: ['套图导出', 'ZIP打包', '批量下载'], category: 'POD套图' },
    { topic: 'POD套图质量检查标准与流程', keywords: ['套图质量', '质量检查', 'POD'], category: 'POD套图' },
    { topic: '不同品类商品的套图模板差异', keywords: ['套图模板', '商品品类', '模板差异'], category: 'POD套图' },
    { topic: 'POD套图自动化流程搭建', keywords: ['POD套图', '自动化', '批量处理'], category: 'POD套图' },
    { topic: '套图模板复用与变体生成技巧', keywords: ['套图模板', '模板复用', '变体'], category: 'POD套图' },
    { topic: 'POD按需印刷商业模式解析', keywords: ['POD', '按需印刷', '商业模式'], category: 'POD套图' },

    // ===== 侵权规避 =====
    { topic: 'Temu侵权检测方法与自查流程', keywords: ['Temu侵权', '侵权检测', '自查'], category: '侵权规避' },
    { topic: 'POD版权风险规避完全指南', keywords: ['POD版权', '侵权规避', '版权风险'], category: '侵权规避' },
    { topic: '图案侵权自查工具与使用方法', keywords: ['图案侵权', '自查工具', '侵权查询'], category: '侵权规避' },
    { topic: '跨境电商常见的侵权类型与案例', keywords: ['跨境侵权', '侵权类型', '案例'], category: '侵权规避' },
    { topic: '如何避免POD图案的版权纠纷', keywords: ['POD版权', '版权纠纷', '侵权规避'], category: '侵权规避' },
    { topic: '商标侵权与专利侵权的区别', keywords: ['商标侵权', '专利侵权', '知识产权'], category: '侵权规避' },
    { topic: 'AI侵权检测在跨境电商中的应用', keywords: ['AI侵权检测', '跨境电商', '智能检测'], category: '侵权规避' },
    { topic: 'Temu平台侵权处罚规则解读', keywords: ['Temu侵权', '处罚规则', '平台政策'], category: '侵权规避' },
    { topic: 'POD设计中的合理使用边界', keywords: ['POD设计', '合理使用', '版权'], category: '侵权规避' },
    { topic: '如何查询图案是否已被注册版权', keywords: ['版权查询', '图案版权', '侵权自查'], category: '侵权规避' },
    { topic: '跨境电商知识产权保护入门', keywords: ['知识产权', '跨境电商', '保护'], category: '侵权规避' },
    { topic: 'POD卖家如何建立侵权防御体系', keywords: ['POD侵权', '防御体系', '风险管理'], category: '侵权规避' },

    // ===== AI 工具 =====
    { topic: 'AI生成商品标题技巧与最佳实践', keywords: ['AI标题生成', '商品标题', 'AI工具'], category: 'AI工具' },
    { topic: 'AI套图工具如何提升设计效率', keywords: ['AI套图', '设计效率', 'AI工具'], category: 'AI工具' },
    { topic: 'GLM大模型在跨境电商中的应用', keywords: ['GLM模型', '跨境电商', 'AI应用'], category: 'AI工具' },
    { topic: '如何用AI优化商品详情页文案', keywords: ['AI文案', '详情页', '商品描述'], category: 'AI工具' },
    { topic: 'AI辅助选品的数据分析方法', keywords: ['AI选品', '数据分析', '选品工具'], category: 'AI工具' },
    { topic: '自定义AI模型接入与配置指南', keywords: ['AI模型接入', '自定义模型', 'API配置'], category: 'AI工具' },
    { topic: '主流AI大模型对比与选择', keywords: ['AI大模型', '模型对比', '大模型选择'], category: 'AI工具' },
    { topic: 'AI生成内容如何通过平台审核', keywords: ['AI生成内容', '平台审核', '合规'], category: 'AI工具' },
    { topic: '用AI批量生成商品描述的方法', keywords: ['AI批量生成', '商品描述', '效率工具'], category: 'AI工具' },
    { topic: 'AI在POD图案设计中的创意应用', keywords: ['AI设计', 'POD图案', '创意'], category: 'AI工具' },
    { topic: 'DeepSeek模型在电商运营中的用法', keywords: ['DeepSeek', '电商运营', 'AI模型'], category: 'AI工具' },
    { topic: '通义千问模型电商场景应用实战', keywords: ['通义千问', '电商场景', 'AI应用'], category: 'AI工具' },
    { topic: 'Kimi大模型使用体验与电商场景', keywords: ['Kimi', '大模型', '电商'], category: 'AI工具' },
    { topic: '智谱AI模型在跨境业务中的价值', keywords: ['智谱AI', '跨境业务', 'GLM'], category: 'AI工具' },
    { topic: '如何选择适合电商的AI模型', keywords: ['AI模型选择', '电商AI', '模型对比'], category: 'AI工具' },

    // ===== 跨境干货 =====
    { topic: '跨境ERP工具对比：妙手、店小秘等', keywords: ['跨境ERP', '妙手', '店小秘', '工具对比'], category: '跨境干货' },
    { topic: '妙手ERP上架操作完整教程', keywords: ['妙手ERP', '上架教程', 'ERP工具'], category: '跨境干货' },
    { topic: '店小秘ERP使用指南与技巧', keywords: ['店小秘', 'ERP使用', '上架工具'], category: '跨境干货' },
    { topic: '半托管与全托管模式深度对比', keywords: ['半托管', '全托管', '模式对比'], category: '跨境干货' },
    { topic: '跨境电商卖家工具链搭建', keywords: ['跨境工具', '工具链', '卖家工具'], category: '跨境干货' },
    { topic: '跨境电商数据分析方法与指标', keywords: ['数据分析', '跨境指标', '运营数据'], category: '跨境干货' },
    { topic: '新手做跨境电商的起步指南', keywords: ['跨境电商', '新手入门', '起步指南'], category: '跨境干货' },
    { topic: '跨境电商选品方法论与工具', keywords: ['跨境选品', '选品方法', '选品工具'], category: '跨境干货' },
    { topic: '跨境物流模式对比与选择', keywords: ['跨境物流', '物流模式', '发货'], category: '跨境干货' },
    { topic: '跨境电商支付与收款方案', keywords: ['跨境支付', '收款', '资金流转'], category: '跨境干货' },
    { topic: '跨境电商多店铺管理技巧', keywords: ['多店铺', '店铺管理', '跨境运营'], category: '跨境干货' },
    { topic: '跨境卖家如何做竞品分析', keywords: ['竞品分析', '跨境卖家', '市场调研'], category: '跨境干货' },
    { topic: '跨境电商季节性选品策略', keywords: ['季节选品', '跨境电商', '选品策略'], category: '跨境干货' },
    { topic: '跨境电商退货处理与售后优化', keywords: ['退货处理', '售后优化', '跨境'], category: '跨境干货' },
    { topic: '跨境电商独立站与平台对比', keywords: ['独立站', '平台对比', '跨境电商'], category: '跨境干货' },

    // ===== 实用技巧 =====
    { topic: '商品图片批量处理与优化技巧', keywords: ['图片处理', '批量优化', '商品图'], category: '实用技巧' },
    { topic: '如何快速制作多SKU商品图', keywords: ['多SKU', '商品图', '批量制作'], category: '实用技巧' },
    { topic: '电商图片压缩与格式选择', keywords: ['图片压缩', '图片格式', '电商图片'], category: '实用技巧' },
    { topic: '商品主图A/B测试方法', keywords: ['主图测试', 'A/B测试', '转化优化'], category: '实用技巧' },
    { topic: '电商图片SEO优化技巧', keywords: ['图片SEO', '电商图片', '搜索引擎'], category: '实用技巧' },
    { topic: '批量修改图片尺寸的工具与方法', keywords: ['批量改图', '图片尺寸', '工具'], category: '实用技巧' },
    { topic: '商品详情页图片排版设计原则', keywords: ['详情页', '图片排版', '设计原则'], category: '实用技巧' },
    { topic: '电商图片水印添加与去除方法', keywords: ['图片水印', '加水印', '去水印'], category: '实用技巧' },
    { topic: '如何给商品图片批量重命名', keywords: ['图片重命名', '批量处理', '文件管理'], category: '实用技巧' },
    { topic: '电商白底图制作标准与工具', keywords: ['白底图', '图片制作', '电商标准'], category: '实用技巧' },
    { topic: '商品图片色彩校正与调色技巧', keywords: ['色彩校正', '调色', '商品图'], category: '实用技巧' },
    { topic: '电商场景图拍摄与后期处理', keywords: ['场景图', '拍摄', '后期处理'], category: '实用技巧' },
    { topic: '如何用模板批量生成商品图', keywords: ['模板生成', '批量商品图', '套图'], category: '实用技巧' },
    { topic: '电商图片素材管理与分类方法', keywords: ['图片素材', '素材管理', '文件分类'], category: '实用技巧' },
    { topic: '商品图片防盗图与版权保护', keywords: ['防盗图', '版权保护', '电商图片'], category: '实用技巧' },

    // ===== 行业趋势 =====
    { topic: '2025年跨境电商行业趋势分析', keywords: ['跨境电商', '行业趋势', '2025'], category: '行业趋势' },
    { topic: 'POD按需印刷市场前景与机会', keywords: ['POD', '按需印刷', '市场前景'], category: '行业趋势' },
    { topic: 'Temu平台2025年政策变化解读', keywords: ['Temu政策', '平台变化', '2025'], category: '行业趋势' },
    { topic: 'AI技术如何改变跨境电商', keywords: ['AI技术', '跨境电商', '技术变革'], category: '行业趋势' },
    { topic: '跨境电商自动化工具发展趋势', keywords: ['自动化工具', '跨境电商', '趋势'], category: '行业趋势' },
    { topic: '半托管模式会成为主流吗', keywords: ['半托管', '电商模式', '趋势'], category: '行业趋势' },
    { topic: '跨境电商SaaS工具生态分析', keywords: ['SaaS工具', '跨境电商', '生态'], category: '行业趋势' },
    { topic: '中国卖家出海的新机遇与挑战', keywords: ['卖家出海', '跨境电商', '机遇挑战'], category: '行业趋势' },
    { topic: 'AI生成内容监管对电商的影响', keywords: ['AI监管', '电商', '合规'], category: '行业趋势' },
    { topic: '跨境电商供应链数字化升级', keywords: ['供应链', '数字化', '跨境电商'], category: '行业趋势' },
  ],
};
